M48
; DRILL file {KiCad 8.0.6-8.0.6-0~ubuntu22.04.1} date 2024-11-29T16:11:12+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-29T16:11:12+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6-8.0.6-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0512
%
G90
G05
T1
X5.7815Y-4.0906
X6.0965Y-4.0906
T2
X5.374Y-1.7933
X5.374Y-2.0295
M30
